# Generated by Django 5.0.4 on 2024-05-05 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cars',
            options={'ordering': ['released'], 'verbose_name': 'машину', 'verbose_name_plural': 'машины'},
        ),
    ]
